# Generated by Django 3.1.7 on 2021-04-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Необходимые очки')),
            ],
            options={
                'verbose_name': 'Уровни',
                'verbose_name_plural': 'Уровни',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Превью')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.category', verbose_name='Категория')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.levels', verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.levels', verbose_name='Уровень доступа'),
        ),
    ]
